[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# Serve static assets first (no redirect)
[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Serve sitemap with correct content type
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  headers = {Content-Type = "application/xml"}

# Handle client-side routing for everything else
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
